version: "3"
services:
  webserver:
    image: nginx:alpine
    container_name: "${SERVER_NAME}-webserver"
    volumes:
      - "./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/config/nginx/sites-enabled:/etc/nginx/sites-enabled"
      - "./docker/config/ssl:/etc/ssl"
      - "./src:/var/www/html"
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    restart: always
    depends_on:
      - php
      - database
  php:
    build:
      context: "./docker/bin/php"
    container_name: "${SERVER_NAME}-php"
    restart: always
    volumes:
      - "./docker/config/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./src:/var/www/html"
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "${SERVER_NAME}-myadmin"
    ports:
        - "8080:80"
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=${MYSQL_HOST}
    restart: always
    depends_on:
        - database
  database:
    build:
      context: "./docker/bin/mysql"
    container_name: "${SERVER_NAME}-mysql"
    restart: "always"
    ports:
      - "${MYSQL_HOST}:${MYSQL_PORT}:3306"
    volumes:
      - "${MYSQL_INITDB_DIR}:/docker-entrypoint-initdb.d"
      - "${MYSQL_DATA_DIR}:/var/lib/mysql"
      - "${MYSQL_LOG_DIR}:/var/log/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  redis:
    container_name: "${SERVER_NAME}-redis"
    image: redis:latest
    ports:
      - "${REDIS_HOST}:${REDIS_PORT}:6379"